catalogMode: prefer

cleanupUnusedCatalogs: true

publicHoistPattern:
  - "*@rbxts*"

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1

packages:
  - src

catalogs:
  build:
    roblox-ts: ^3.0.0
    typescript: ^5.9.3
  lint:
    "@isentinel/eslint-config": ^4.7.6
    eslint: ^9.39.2
    eslint-plugin-pnpm: ^1.4.3
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-naming-convention: ^2.5.1
    eslint-plugin-react-roblox-hooks: 5.1.0-rbx.1
    eslint-plugin-react-x: ^2.5.1
  script:
    jiti: ^2.6.1
  types:
    "@isentinel/tsconfig": ^1.2.0
    "@rbxts/compiler-types": 3.0.0-types.0
    "@rbxts/types": ^1.0.896
configDependencies:
  "@pnpm/trusted-deps": 0.1.0+sha512-IERT0uXPBnSZGsCmoSuPzYNWhXWWnKkuc9q78KzLdmDWJhnrmvc7N4qaHJmaNKIusdCH2riO3iE34Osohj6n8w==
onlyBuiltDependencies:
  - unrs-resolver
